server:
  servlet:
    session:
      cookie:
        same-site: lax

spring:
  security:
    debug: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gesellschaft
    username: root
    password: 65
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: DEBUG